export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_EDIT_ID = 'CHANGE_EDIT_ID';
export const CLEAR_SERVICE_FIELDS = 'CLEAR_SERVICE_FIELDS';
